spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/howalog
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true

logging:
  level:
    org.hibernate.SQL: debug